const bookNames = [
    {book:'Genesis', code:'GEN', section:'OT'},
    {book:'Exodus', code:'EXO', section:'OT'},
    {book:'Leviticus', code:'LEV', section:'OT'},
    {book:'Numbers', code:'NUM', section:'OT'},
    {book:'Deuteronomy', code:'DEU', section:'OT'},
    {book:'Joshua', code:'JOS', section:'OT'},
    {book:'Judges', code:'JDG', section:'OT'},
    {book:'Ruth', code:'RUT', section:'OT'},
    {book:'1 Samuel', code:'1SA', section:'OT'},
    {book:'2 Samuel', code:'2SA', section:'OT'},
    {book:'1 Kings', code:'1KI', section:'OT'},
    {book:'2 Kings', code:'2KI', section:'OT'},
    {book:'1 Chronicles', code:'1CH', section:'OT'},
    {book:'2 Chronicles', code:'2CH', section:'OT'},
    {book:'Ezra', code:'EZR', section:'OT'},
    {book:'Nehemiah', code:'NEH', section:'OT'},
    {book:'Esther', code:'EST', section:'OT'},
    {book:'Job', code:'JOB', section:'OT'},
    {book:'Psalms', code:'PSA', section:'OT'},
    {book:'Proverbs', code:'PRO', section:'OT'},
    {book:'Ecclesiastes', code:'ECC', section:'OT'},
    {book:'Song of Solomon', code:'SNG', section:'OT'},
    {book:'Isaiah', code:'ISA', section:'OT'},
    {book:'Jeremiah', code:'JER', section:'OT'},
    {book:'Lamentations', code:'LAM', section:'OT'},
    {book:'Ezekiel', code:'EZK', section:'OT'},
    {book:'Daniel', code:'DAN', section:'OT'},
    {book:'Hosea', code:'HOS', section:'OT'},
    {book:'Joel', code:'JOL', section:'OT'},
    {book:'Amos', code:'AMO', section:'OT'},
    {book:'Obadiah', code:'OBA', section:'OT'},
    {book:'Jonah', code:'JON', section:'OT'},
    {book:'Micah', code:'MIC', section:'OT'},
    {book:'Nahum', code:'NAM', section:'OT'},
    {book:'Habakkuk', code:'HAB', section:'OT'},
    {book:'Zephaniah', code:'ZEP', section:'OT'},
    {book:'Haggai', code:'HAG', section:'OT'},
    {book:'Zechariah', code:'ZEC', section:'OT'},
    {book:'Malachi', code:'MAL', section:'OT'},
    {book:'Matthew', code:'MAT', section:'NT'},
    {book:'Mark', code:'MRK', section:'NT'},
    {book:'Luke', code:'LUK', section:'NT'},
    {book:'John', code:'JHN', section:'NT'},
    {book:'Acts', code:'ACT', section:'NT'},
    {book:'Romans', code:'ROM', section:'NT'},
    {book:'1 Corinthians', code:'1CO', section:'NT'},
    {book:'2 Corinthians', code:'2CO', section:'NT'},
    {book:'Galatians', code:'GAL', section:'NT'},
    {book:'Ephesians', code:'EPH', section:'NT'},
    {book:'Philippians', code:'PHP', section:'NT'},
    {book:'Colossians', code:'COL', section:'NT'},
    {book:'1 Thessalonians', code:'1TH', section:'NT'},
    {book:'2 Thessalonians', code:'2TH', section:'NT'},
    {book:'1 Timothy', code:'1TI', section:'NT'},
    {book:'2 Timothy', code:'2TI', section:'NT'},
    {book:'Titus', code:'TIT', section:'NT'},
    {book:'Philemon', code:'PHM', section:'NT'},
    {book:'Hebrews', code:'HEB', section:'NT'},
    {book:'James', code:'JAS', section:'NT'},
    {book:'1 Peter', code:'1PE', section:'NT'},
    {book:'2 Peter', code:'2PE', section:'NT'},
    {book:'1 John', code:'1JN', section:'NT'},
    {book:'2 John', code:'2JN', section:'NT'},
    {book:'3 John', code:'3JN', section:'NT'},
    {book:'Jude', code:'JUD', section:'NT'},
    {book:'Revelation', code:'REV', section:'NT'}
]

export default bookNames;